### ISSUE TITLE
Club Tracker Assistance

### ISSUE THREAD

**Issue by wid2001** [picasticks/StravaClubTracker#1]
This isn't an issue so much as a request for additional resources for setting up the example.  I work for a nonprofit and attempting to utilize a version of your tracker in the same way you mentioned.  Some of this is a little above my head and I need help getting started with the example.  I have followed the instructions provided but when I attempt to load the php file in my browser things fall apart.  Can you point me in the right direction for learning how to get started with your tracker.  Any assistance you can provide would be appreciated but if you have other projects that prevent you from giving up the time I understand.

**Comment by picasticks** [comment]
That's great, and thanks for your interest in the library!

It's definitely meant for people who are experienced PHP developers and familiar with Composer. The easiest way to get started with the example is to install the [composer package](https://packagist.org/packages/picasticks/stravaclubtracker), then follow the quick start instructions. PHP 7.4 or higher is required. And lines 15-36 of the `example_update.php` script definitely need to be edited to define your Club IDs, Strava API credentials, the URL of the script, and start/end dates. 

This isn't my day job so I can't provide a ton of end user support, but if you have any specific questions I'll try to help, you can reply to this issue.

Since you're at a nonprofit you might want to look at some ready-made options for running fundraising challenges, you've probably seen some of these on Strava. For example I know that Blackbaud has a nice integration for [virtual fundraising events](https://blog.justgiving.com/strava-enhance-charity-supporter-experience/).

**Comment by wid2001** [comment]
Awesome and thanks for the reply. I’ll check out some of those options.

Spencer
